# Generated by Django 3.2.7 on 2021-09-18 12:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1', models.CharField(max_length=100, verbose_name='Participant 1 Name')),
                ('email_1', models.EmailField(max_length=254, unique=True, verbose_name='Participant 1 Email')),
                ('phone_number_1', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')], verbose_name='Participant 1 Phone Number')),
                ('name_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Participant 2 Name')),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Participant 2 Email')),
                ('phone_number_2', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be valid', regex='^\\+?1?\\d{9,15}$')], verbose_name='Participant 2 Phone Number')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=700, verbose_name='Question statement')),
                ('is_active', models.BooleanField(default=True, help_text='Should question be included in quiz?', verbose_name='Active')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('has_image', models.BooleanField(default=False, help_text='Does question have image?', verbose_name='Image')),
                ('category', models.CharField(choices=[('C++', 'C++'), ('C', 'C')], default='C++', max_length=5, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(blank=True, max_length=500, null=True)),
                ('answers', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_a', models.CharField(max_length=500, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=500, verbose_name='Option C')),
                ('option_d', models.CharField(max_length=500, verbose_name='Option D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
    ]
