# Generated by Django 3.2.7 on 2021-09-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Level one', 'Level 1'), ('Level two', 'Level 2'), ('Level three', 'Level 3')], default='C++', max_length=11, verbose_name='Category'),
        ),
    ]
