# Generated by Django 3.2.7 on 2021-09-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='exam',
            new_name='Level',
        ),
        migrations.RemoveField(
            model_name='result',
            name='date',
        ),
    ]
