# Generated by Django 3.2.7 on 2021-09-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('organization', models.CharField(max_length=50)),
                ('certification', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('uid', models.CharField(default=0, max_length=70)),
            ],
        ),
    ]
